/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.jana.karim.avro.model.destination;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CustomerInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3656533641652224945L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerInfo\",\"namespace\":\"com.jana.karim.avro.model.destination\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"record\",\"name\":\"Name\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"nickname\",\"type\":\"string\"}]}},{\"name\":\"address\",\"type\":{\"type\":\"record\",\"name\":\"MailAddress\",\"fields\":[{\"name\":\"city\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public com.jana.karim.avro.model.destination.Name name;
  @Deprecated public com.jana.karim.avro.model.destination.MailAddress address;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CustomerInfo() {}

  /**
   * All-args constructor.
   */
  public CustomerInfo(com.jana.karim.avro.model.destination.Name name, com.jana.karim.avro.model.destination.MailAddress address) {
    this.name = name;
    this.address = address;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return address;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (com.jana.karim.avro.model.destination.Name)value$; break;
    case 1: address = (com.jana.karim.avro.model.destination.MailAddress)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public com.jana.karim.avro.model.destination.Name getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(com.jana.karim.avro.model.destination.Name value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'address' field.
   */
  public com.jana.karim.avro.model.destination.MailAddress getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(com.jana.karim.avro.model.destination.MailAddress value) {
    this.address = value;
  }

  /**
   * Creates a new CustomerInfo RecordBuilder.
   * @return A new CustomerInfo RecordBuilder
   */
  public static com.jana.karim.avro.model.destination.CustomerInfo.Builder newBuilder() {
    return new com.jana.karim.avro.model.destination.CustomerInfo.Builder();
  }
  
  /**
   * Creates a new CustomerInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerInfo RecordBuilder
   */
  public static com.jana.karim.avro.model.destination.CustomerInfo.Builder newBuilder(com.jana.karim.avro.model.destination.CustomerInfo.Builder other) {
    return new com.jana.karim.avro.model.destination.CustomerInfo.Builder(other);
  }
  
  /**
   * Creates a new CustomerInfo RecordBuilder by copying an existing CustomerInfo instance.
   * @param other The existing instance to copy.
   * @return A new CustomerInfo RecordBuilder
   */
  public static com.jana.karim.avro.model.destination.CustomerInfo.Builder newBuilder(com.jana.karim.avro.model.destination.CustomerInfo other) {
    return new com.jana.karim.avro.model.destination.CustomerInfo.Builder(other);
  }
  
  /**
   * RecordBuilder for CustomerInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerInfo>
    implements org.apache.avro.data.RecordBuilder<CustomerInfo> {

    private com.jana.karim.avro.model.destination.Name name;
    private com.jana.karim.avro.model.destination.Name.Builder nameBuilder;
    private com.jana.karim.avro.model.destination.MailAddress address;
    private com.jana.karim.avro.model.destination.MailAddress.Builder addressBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(com.jana.karim.avro.model.destination.CustomerInfo.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.jana.karim.avro.model.destination.CustomerInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (other.hasNameBuilder()) {
        this.nameBuilder = com.jana.karim.avro.model.destination.Name.newBuilder(other.getNameBuilder());
      }
      if (isValidValue(fields()[1], other.address)) {
        this.address = data().deepCopy(fields()[1].schema(), other.address);
        fieldSetFlags()[1] = true;
      }
      if (other.hasAddressBuilder()) {
        this.addressBuilder = com.jana.karim.avro.model.destination.MailAddress.newBuilder(other.getAddressBuilder());
      }
    }
    
    /**
     * Creates a Builder by copying an existing CustomerInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.jana.karim.avro.model.destination.CustomerInfo other) {
            super(com.jana.karim.avro.model.destination.CustomerInfo.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      this.nameBuilder = null;
      if (isValidValue(fields()[1], other.address)) {
        this.address = data().deepCopy(fields()[1].schema(), other.address);
        fieldSetFlags()[1] = true;
      }
      this.addressBuilder = null;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public com.jana.karim.avro.model.destination.Name getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder setName(com.jana.karim.avro.model.destination.Name value) {
      validate(fields()[0], value);
      this.nameBuilder = null;
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'name' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.jana.karim.avro.model.destination.Name.Builder getNameBuilder() {
      if (nameBuilder == null) {
        if (hasName()) {
          setNameBuilder(com.jana.karim.avro.model.destination.Name.newBuilder(name));
        } else {
          setNameBuilder(com.jana.karim.avro.model.destination.Name.newBuilder());
        }
      }
      return nameBuilder;
    }

    /**
     * Sets the Builder instance for the 'name' field
     * @return This builder.
     */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder setNameBuilder(com.jana.karim.avro.model.destination.Name.Builder value) {
      clearName();
      nameBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'name' field has an active Builder instance
     * @return True if the 'name' field has an active Builder instance
     */
    public boolean hasNameBuilder() {
      return nameBuilder != null;
    }

    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder clearName() {
      name = null;
      nameBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public com.jana.karim.avro.model.destination.MailAddress getAddress() {
      return address;
    }

    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder setAddress(com.jana.karim.avro.model.destination.MailAddress value) {
      validate(fields()[1], value);
      this.addressBuilder = null;
      this.address = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'address' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.jana.karim.avro.model.destination.MailAddress.Builder getAddressBuilder() {
      if (addressBuilder == null) {
        if (hasAddress()) {
          setAddressBuilder(com.jana.karim.avro.model.destination.MailAddress.newBuilder(address));
        } else {
          setAddressBuilder(com.jana.karim.avro.model.destination.MailAddress.newBuilder());
        }
      }
      return addressBuilder;
    }

    /**
     * Sets the Builder instance for the 'address' field
     * @return This builder.
     */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder setAddressBuilder(com.jana.karim.avro.model.destination.MailAddress.Builder value) {
      clearAddress();
      addressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'address' field has an active Builder instance
     * @return True if the 'address' field has an active Builder instance
     */
    public boolean hasAddressBuilder() {
      return addressBuilder != null;
    }

    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder clearAddress() {
      address = null;
      addressBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public CustomerInfo build() {
      try {
        CustomerInfo record = new CustomerInfo();
        if (nameBuilder != null) {
          record.name = this.nameBuilder.build();
        } else {
          record.name = fieldSetFlags()[0] ? this.name : (com.jana.karim.avro.model.destination.Name) defaultValue(fields()[0]);
        }
        if (addressBuilder != null) {
          record.address = this.addressBuilder.build();
        } else {
          record.address = fieldSetFlags()[1] ? this.address : (com.jana.karim.avro.model.destination.MailAddress) defaultValue(fields()[1]);
        }
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
