/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.jana.karim.avro.model.destination;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CustomerInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4805032091410070536L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerInfo\",\"namespace\":\"com.jana.karim.avro.model.destination\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Name\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"nickname\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null},{\"name\":\"addresses\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"MailAddress\",\"fields\":[{\"name\":\"city\",\"type\":[\"null\",\"string\"],\"default\":null}]}}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public com.jana.karim.avro.model.destination.Name name;
  @Deprecated public java.util.List<com.jana.karim.avro.model.destination.MailAddress> addresses;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CustomerInfo() {}

  /**
   * All-args constructor.
   */
  public CustomerInfo(java.lang.CharSequence id, com.jana.karim.avro.model.destination.Name name, java.util.List<com.jana.karim.avro.model.destination.MailAddress> addresses) {
    this.id = id;
    this.name = name;
    this.addresses = addresses;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return addresses;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (com.jana.karim.avro.model.destination.Name)value$; break;
    case 2: addresses = (java.util.List<com.jana.karim.avro.model.destination.MailAddress>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public com.jana.karim.avro.model.destination.Name getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(com.jana.karim.avro.model.destination.Name value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'addresses' field.
   */
  public java.util.List<com.jana.karim.avro.model.destination.MailAddress> getAddresses() {
    return addresses;
  }

  /**
   * Sets the value of the 'addresses' field.
   * @param value the value to set.
   */
  public void setAddresses(java.util.List<com.jana.karim.avro.model.destination.MailAddress> value) {
    this.addresses = value;
  }

  /**
   * Creates a new CustomerInfo RecordBuilder.
   * @return A new CustomerInfo RecordBuilder
   */
  public static com.jana.karim.avro.model.destination.CustomerInfo.Builder newBuilder() {
    return new com.jana.karim.avro.model.destination.CustomerInfo.Builder();
  }
  
  /**
   * Creates a new CustomerInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerInfo RecordBuilder
   */
  public static com.jana.karim.avro.model.destination.CustomerInfo.Builder newBuilder(com.jana.karim.avro.model.destination.CustomerInfo.Builder other) {
    return new com.jana.karim.avro.model.destination.CustomerInfo.Builder(other);
  }
  
  /**
   * Creates a new CustomerInfo RecordBuilder by copying an existing CustomerInfo instance.
   * @param other The existing instance to copy.
   * @return A new CustomerInfo RecordBuilder
   */
  public static com.jana.karim.avro.model.destination.CustomerInfo.Builder newBuilder(com.jana.karim.avro.model.destination.CustomerInfo other) {
    return new com.jana.karim.avro.model.destination.CustomerInfo.Builder(other);
  }
  
  /**
   * RecordBuilder for CustomerInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerInfo>
    implements org.apache.avro.data.RecordBuilder<CustomerInfo> {

    private java.lang.CharSequence id;
    private com.jana.karim.avro.model.destination.Name name;
    private com.jana.karim.avro.model.destination.Name.Builder nameBuilder;
    private java.util.List<com.jana.karim.avro.model.destination.MailAddress> addresses;

    /** Creates a new Builder */
    private Builder() {
      super(com.jana.karim.avro.model.destination.CustomerInfo.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.jana.karim.avro.model.destination.CustomerInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (other.hasNameBuilder()) {
        this.nameBuilder = com.jana.karim.avro.model.destination.Name.newBuilder(other.getNameBuilder());
      }
      if (isValidValue(fields()[2], other.addresses)) {
        this.addresses = data().deepCopy(fields()[2].schema(), other.addresses);
        fieldSetFlags()[2] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing CustomerInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.jana.karim.avro.model.destination.CustomerInfo other) {
            super(com.jana.karim.avro.model.destination.CustomerInfo.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      this.nameBuilder = null;
      if (isValidValue(fields()[2], other.addresses)) {
        this.addresses = data().deepCopy(fields()[2].schema(), other.addresses);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public com.jana.karim.avro.model.destination.Name getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder setName(com.jana.karim.avro.model.destination.Name value) {
      validate(fields()[1], value);
      this.nameBuilder = null;
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'name' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.jana.karim.avro.model.destination.Name.Builder getNameBuilder() {
      if (nameBuilder == null) {
        if (hasName()) {
          setNameBuilder(com.jana.karim.avro.model.destination.Name.newBuilder(name));
        } else {
          setNameBuilder(com.jana.karim.avro.model.destination.Name.newBuilder());
        }
      }
      return nameBuilder;
    }

    /**
     * Sets the Builder instance for the 'name' field
     * @return This builder.
     */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder setNameBuilder(com.jana.karim.avro.model.destination.Name.Builder value) {
      clearName();
      nameBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'name' field has an active Builder instance
     * @return True if the 'name' field has an active Builder instance
     */
    public boolean hasNameBuilder() {
      return nameBuilder != null;
    }

    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder clearName() {
      name = null;
      nameBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'addresses' field.
      * @return The value.
      */
    public java.util.List<com.jana.karim.avro.model.destination.MailAddress> getAddresses() {
      return addresses;
    }

    /**
      * Sets the value of the 'addresses' field.
      * @param value The value of 'addresses'.
      * @return This builder.
      */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder setAddresses(java.util.List<com.jana.karim.avro.model.destination.MailAddress> value) {
      validate(fields()[2], value);
      this.addresses = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'addresses' field has been set.
      * @return True if the 'addresses' field has been set, false otherwise.
      */
    public boolean hasAddresses() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'addresses' field.
      * @return This builder.
      */
    public com.jana.karim.avro.model.destination.CustomerInfo.Builder clearAddresses() {
      addresses = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public CustomerInfo build() {
      try {
        CustomerInfo record = new CustomerInfo();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (nameBuilder != null) {
          record.name = this.nameBuilder.build();
        } else {
          record.name = fieldSetFlags()[1] ? this.name : (com.jana.karim.avro.model.destination.Name) defaultValue(fields()[1]);
        }
        record.addresses = fieldSetFlags()[2] ? this.addresses : (java.util.List<com.jana.karim.avro.model.destination.MailAddress>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
