/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.jana.karim.avro.model.source;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Address extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1139687393875306913L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"com.jana.karim.avro.model.source\",\"fields\":[{\"name\":\"address_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"city\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"name_id\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence address_id;
  @Deprecated public java.lang.CharSequence city;
  @Deprecated public java.lang.CharSequence name_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Address() {}

  /**
   * All-args constructor.
   */
  public Address(java.lang.CharSequence address_id, java.lang.CharSequence city, java.lang.CharSequence name_id) {
    this.address_id = address_id;
    this.city = city;
    this.name_id = name_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return address_id;
    case 1: return city;
    case 2: return name_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: address_id = (java.lang.CharSequence)value$; break;
    case 1: city = (java.lang.CharSequence)value$; break;
    case 2: name_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'address_id' field.
   */
  public java.lang.CharSequence getAddressId() {
    return address_id;
  }

  /**
   * Sets the value of the 'address_id' field.
   * @param value the value to set.
   */
  public void setAddressId(java.lang.CharSequence value) {
    this.address_id = value;
  }

  /**
   * Gets the value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }

  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'name_id' field.
   */
  public java.lang.CharSequence getNameId() {
    return name_id;
  }

  /**
   * Sets the value of the 'name_id' field.
   * @param value the value to set.
   */
  public void setNameId(java.lang.CharSequence value) {
    this.name_id = value;
  }

  /**
   * Creates a new Address RecordBuilder.
   * @return A new Address RecordBuilder
   */
  public static com.jana.karim.avro.model.source.Address.Builder newBuilder() {
    return new com.jana.karim.avro.model.source.Address.Builder();
  }
  
  /**
   * Creates a new Address RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Address RecordBuilder
   */
  public static com.jana.karim.avro.model.source.Address.Builder newBuilder(com.jana.karim.avro.model.source.Address.Builder other) {
    return new com.jana.karim.avro.model.source.Address.Builder(other);
  }
  
  /**
   * Creates a new Address RecordBuilder by copying an existing Address instance.
   * @param other The existing instance to copy.
   * @return A new Address RecordBuilder
   */
  public static com.jana.karim.avro.model.source.Address.Builder newBuilder(com.jana.karim.avro.model.source.Address other) {
    return new com.jana.karim.avro.model.source.Address.Builder(other);
  }
  
  /**
   * RecordBuilder for Address instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Address>
    implements org.apache.avro.data.RecordBuilder<Address> {

    private java.lang.CharSequence address_id;
    private java.lang.CharSequence city;
    private java.lang.CharSequence name_id;

    /** Creates a new Builder */
    private Builder() {
      super(com.jana.karim.avro.model.source.Address.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.jana.karim.avro.model.source.Address.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.address_id)) {
        this.address_id = data().deepCopy(fields()[0].schema(), other.address_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name_id)) {
        this.name_id = data().deepCopy(fields()[2].schema(), other.name_id);
        fieldSetFlags()[2] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing Address instance
     * @param other The existing instance to copy.
     */
    private Builder(com.jana.karim.avro.model.source.Address other) {
            super(com.jana.karim.avro.model.source.Address.SCHEMA$);
      if (isValidValue(fields()[0], other.address_id)) {
        this.address_id = data().deepCopy(fields()[0].schema(), other.address_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name_id)) {
        this.name_id = data().deepCopy(fields()[2].schema(), other.name_id);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'address_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddressId() {
      return address_id;
    }

    /**
      * Sets the value of the 'address_id' field.
      * @param value The value of 'address_id'.
      * @return This builder.
      */
    public com.jana.karim.avro.model.source.Address.Builder setAddressId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.address_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'address_id' field has been set.
      * @return True if the 'address_id' field has been set, false otherwise.
      */
    public boolean hasAddressId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'address_id' field.
      * @return This builder.
      */
    public com.jana.karim.avro.model.source.Address.Builder clearAddressId() {
      address_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }

    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public com.jana.karim.avro.model.source.Address.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.city = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public com.jana.karim.avro.model.source.Address.Builder clearCity() {
      city = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getNameId() {
      return name_id;
    }

    /**
      * Sets the value of the 'name_id' field.
      * @param value The value of 'name_id'.
      * @return This builder.
      */
    public com.jana.karim.avro.model.source.Address.Builder setNameId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.name_id = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'name_id' field has been set.
      * @return True if the 'name_id' field has been set, false otherwise.
      */
    public boolean hasNameId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name_id' field.
      * @return This builder.
      */
    public com.jana.karim.avro.model.source.Address.Builder clearNameId() {
      name_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Address build() {
      try {
        Address record = new Address();
        record.address_id = fieldSetFlags()[0] ? this.address_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.city = fieldSetFlags()[1] ? this.city : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.name_id = fieldSetFlags()[2] ? this.name_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
