/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.jana.karim.avro.model.source;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface UserData {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"UserData\",\"namespace\":\"com.jana.karim.avro.model.source\",\"types\":[{\"type\":\"record\",\"name\":\"User\",\"fields\":[{\"name\":\"name_id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"nickname\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"address_id\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"name_id\",\"type\":\"string\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends UserData {
    public static final org.apache.avro.Protocol PROTOCOL = com.jana.karim.avro.model.source.UserData.PROTOCOL;
  }
}